#!/bin/sh
hcitool scan > /home/root/scripts/btres
lines="$(cat /home/root/scripts/btres | wc -l)"
lines=$(($lines-1))
rm -f btnames
if [ $lines != 0 ]; then
        comm="cat /home/root/scripts/btres | tail -n${lines} > /home/root/scripts/btnames"
        eval $comm
	comm="cat /home/root/scripts/btnames | /home/root/scripts/btc2"
	echo "bt names created"
	comm="cat /home/root/scripts/btnames | /home/root/scripts/btc2 > /home/root/smartdoor/db/newbt.db"
	eval $comm
else
	comm="echo null > /home/root/scripts/btnames"
	eval $comm
	comm="echo {} > /home/root/smartdoor/db/newbt.db"
	eval $comm
fi

