#!/bin/bash
echo "{ "
lines=`cat /home/root/scripts/btnames | wc -l`
i=0
while read line; do
	(( i++ ))
	mac=`echo $line | sed -e "s/[[:space:]]\+/ /g" | cut -d" " -f1`
	name=`echo $line | sed -e "s/[[:space:]]\+/ /g" | cut -d" " -f2-`
	if [[ $i == ${lines} ]]; then 
	echo "\"${mac}\":\"${name}\""
	else
	 echo "\"${mac}\":\"${name}\","
	fi
done

echo " }"
